services:
  postgres:
    image: 'postgres:latest'
    container_name: medical-control-postgres
    environment:
      - 'POSTGRES_DB=medical-control'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=user'
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres:

networks:
  default:
    name: local-network